require:
  - rubocop-performance

Layout/LineLength:
  Max: 120
Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

AllCops:
  DisplayCopNames: true
Style/FrozenStringLiteralComment:
  Enabled: false
