require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/*'

Style/RaiseArgs:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'site_mercado.gemspec'

Metrics/MethodLength:
  Max: 13

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
