---
env:
  global:
    - CC_TEST_REPORTER_ID=33e2f46072e77a9cb6ac90008241744829ab80fa0903e53795f9452b41a6b4e9

sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: gem install bundler -v 2.1.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bash bin/setup
  - bundle exec rubocop --fail-fast
  - bundle exec rspec --fail-fast
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
